#!/usr/bin/env bash

set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
ENV_PORT="${ENV_PORT:-36001}"
ENV_ADDR="http://127.0.0.1:${ENV_PORT}"

CONDA_SH="${CONDA_SH:-/home/yexuyan/miniconda3/etc/profile.d/conda.sh}"
ALFWORLD_ENV="${ALFWORLD_ENV:-/idfsdata/yexuyan/conda_envs/agentenv-alfworld}"
TRAIN_ENV="${TRAIN_ENV:-/idfsdata/yexuyan/conda_envs/agentgym-rl-webshop}"
ALFWORLD_DATA="${ALFWORLD_DATA:-/idfsdata/yexuyan/alfworld_data}"

CUDA_VISIBLE_DEVICES="${CUDA_VISIBLE_DEVICES:-0,1,2,3}"
MODEL_PATH="${MODEL_PATH:-/idfsdata/yexuyan/AgentGym-RL/models/Qwen2.5-7B-Instruct}"
WANDB_MODE="${WANDB_MODE:-online}"
WANDB_ANONYMOUS="${WANDB_ANONYMOUS:-allow}"
WANDB_ENTITY="${WANDB_ENTITY:-}"
WANDB_BASE_URL="${WANDB_BASE_URL:-https://api.wandb.ai}"
PROJECT_NAME="${PROJECT_NAME:-ALFWorld}"

# Keep defaults aligned with historical ALFWorld GRPO score run.
KL_COEF="${KL_COEF:-0.001}"
POLICY_LR="${POLICY_LR:-1e-6}"
CRITIC_LR="${CRITIC_LR:-1e-5}"
ROLLOUT_N="${ROLLOUT_N:-8}"
TRAIN_BATCH_SIZE="${TRAIN_BATCH_SIZE:-8}"
PPO_MINI_BATCH_SIZE="${PPO_MINI_BATCH_SIZE:-2}"
PPO_MICRO_BATCH_SIZE_PER_GPU="${PPO_MICRO_BATCH_SIZE_PER_GPU:-1}"
PPO_EPOCHS="${PPO_EPOCHS:-2}"
TOTAL_EPOCHS="${TOTAL_EPOCHS:-2}"
TOTAL_TRAINING_STEPS="${TOTAL_TRAINING_STEPS:-}"
MAX_ROUNDS="${MAX_ROUNDS:-30}"
AGENT_MAX_ROUNDS="${AGENT_MAX_ROUNDS:-10}"
MAX_PROMPT_LENGTH="${MAX_PROMPT_LENGTH:-1024}"
MAX_RESPONSE_LENGTH="${MAX_RESPONSE_LENGTH:-6000}"
MAX_MODEL_LEN="${MAX_MODEL_LEN:-16384}"
MAX_TOKENS_PER_TURN="${MAX_TOKENS_PER_TURN:-200}"
ROLLOUT_GPU_MEMORY_UTILIZATION="${ROLLOUT_GPU_MEMORY_UTILIZATION:-0.70}"
REWARD_MODE="${REWARD_MODE:-score}"
ORM_SUCCESS_SCORE="${ORM_SUCCESS_SCORE:-100.0}"
PAD_TO_MAX_RESPONSE_LENGTH="${PAD_TO_MAX_RESPONSE_LENGTH:-0}"
SAVE_FREQ="${SAVE_FREQ:-50}"
REMOVE_PREVIOUS_CKPT_IN_SAVE="${REMOVE_PREVIOUS_CKPT_IN_SAVE:-0}"
MAX_LOCAL_CKPT_TO_KEEP="${MAX_LOCAL_CKPT_TO_KEEP:-6}"
RESUME_MODE="${RESUME_MODE:-auto}"
RESUME_FROM_PATH="${RESUME_FROM_PATH:-0}"

ENABLE_WMC="${ENABLE_WMC:-0}"
WMC_COEFF="${WMC_COEFF:-0.001}"
ENABLE_ERC="${ENABLE_ERC:-0}"
ERC_MU_BASE="${ERC_MU_BASE:-1.0}"
ERC_MU_EXP="${ERC_MU_EXP:-2.0}"
ERC_ETA_WM="${ERC_ETA_WM:-3.0}"
ERC_LAMBDA_WM="${ERC_LAMBDA_WM:-1.0}"
ERC_CLIPPING_TYPE="${ERC_CLIPPING_TYPE:-global}"
ERC_CLIPPING_METHOD="${ERC_CLIPPING_METHOD:-mask}"
ERC_MOMENTUM="${ERC_MOMENTUM:-0.9}"

# Use short /idfsdata runtime paths to avoid unix socket path-length issues.
RUNTIME_BASE="${RUNTIME_BASE:-/idfsdata/yexuyan/r}"
RAY_TMPDIR="${RAY_TMPDIR:-/idfsdata/yexuyan/ra}"
TMPDIR="${TMPDIR:-/idfsdata/yexuyan/te}"
TMP="${TMP:-${TMPDIR}}"
TEMP="${TEMP:-${TMPDIR}}"
HF_HOME="${HF_HOME:-/idfsdata/yexuyan/he}"
TRANSFORMERS_CACHE="${TRANSFORMERS_CACHE:-${HF_HOME}/hub}"
XDG_CACHE_HOME="${XDG_CACHE_HOME:-/idfsdata/yexuyan/xe}"
WANDB_DIR="${WANDB_DIR:-/idfsdata/yexuyan/we}"
WANDB_CACHE_DIR="${WANDB_CACHE_DIR:-${WANDB_DIR}/.cache}"
WANDB_CONFIG_DIR="${WANDB_CONFIG_DIR:-${WANDB_DIR}/.config}"

BASE_MODEL_NAME="$(basename "${MODEL_PATH}")"
RUN_TS="$(date -u +%Y%m%d_%H%M%S)"
EXP_NAME="${EXP_NAME:-ALFWORLD_PPO_${BASE_MODEL_NAME}_${RUN_TS}}"

ENV_SESSION="${ENV_SESSION:-alfworld_env_${ENV_PORT}_${RUN_TS}}"
TRAIN_SESSION="${TRAIN_SESSION:-alfworld_ppo_${RUN_TS}}"
ENV_LOG="${ROOT}/runlogs/${ENV_SESSION}.log"
TRAIN_LOG="${ROOT}/runlogs/${EXP_NAME}/train.log"

mkdir -p \
  "${ROOT}/runlogs/${EXP_NAME}" \
  "${ALFWORLD_DATA}" \
  "${RUNTIME_BASE}" \
  "${RAY_TMPDIR}" \
  "${TMPDIR}" \
  "${HF_HOME}" \
  "${TRANSFORMERS_CACHE}" \
  "${XDG_CACHE_HOME}" \
  "${WANDB_DIR}" \
  "${WANDB_CACHE_DIR}" \
  "${WANDB_CONFIG_DIR}"

if tmux has-session -t "${ENV_SESSION}" 2>/dev/null; then
  echo "tmux session already exists: ${ENV_SESSION}"
  exit 1
fi
if tmux has-session -t "${TRAIN_SESSION}" 2>/dev/null; then
  echo "tmux session already exists: ${TRAIN_SESSION}"
  exit 1
fi

tmux new-session -d -s "${ENV_SESSION}" \
  "cd ${ROOT} && CONDA_SH=${CONDA_SH} ALFWORLD_ENV=${ALFWORLD_ENV} HOST=127.0.0.1 PORT=${ENV_PORT} LOG_PATH=${ENV_LOG} ALFWORLD_DATA=${ALFWORLD_DATA} TMPDIR=${TMPDIR} TMP=${TMP} TEMP=${TEMP} HF_HOME=${HF_HOME} TRANSFORMERS_CACHE=${TRANSFORMERS_CACHE} XDG_CACHE_HOME=${XDG_CACHE_HOME} bash ${ROOT}/scripts/run_alfworld_env_service.sh"

for _ in $(seq 1 120); do
  if curl --noproxy '*' -sf "${ENV_ADDR}/" >/dev/null; then
    break
  fi
  sleep 2
done

if ! curl --noproxy '*' -sf "${ENV_ADDR}/" >/dev/null; then
  echo "ALFWorld service did not become healthy on ${ENV_ADDR}"
  exit 1
fi

tmux new-session -d -s "${TRAIN_SESSION}" \
  "cd ${ROOT} && CONDA_SH=${CONDA_SH} TRAIN_ENV=${TRAIN_ENV} CUDA_VISIBLE_DEVICES=${CUDA_VISIBLE_DEVICES} ENV_ADDR=${ENV_ADDR} MODEL_PATH=${MODEL_PATH} WANDB_MODE=${WANDB_MODE} WANDB_ANONYMOUS=${WANDB_ANONYMOUS} WANDB_ENTITY=${WANDB_ENTITY} WANDB_BASE_URL=${WANDB_BASE_URL} PROJECT_NAME=${PROJECT_NAME} KL_COEF=${KL_COEF} POLICY_LR=${POLICY_LR} CRITIC_LR=${CRITIC_LR} ROLLOUT_N=${ROLLOUT_N} TRAIN_BATCH_SIZE=${TRAIN_BATCH_SIZE} PPO_MINI_BATCH_SIZE=${PPO_MINI_BATCH_SIZE} PPO_MICRO_BATCH_SIZE_PER_GPU=${PPO_MICRO_BATCH_SIZE_PER_GPU} PPO_EPOCHS=${PPO_EPOCHS} TOTAL_EPOCHS=${TOTAL_EPOCHS} TOTAL_TRAINING_STEPS=${TOTAL_TRAINING_STEPS} MAX_ROUNDS=${MAX_ROUNDS} AGENT_MAX_ROUNDS=${AGENT_MAX_ROUNDS} MAX_PROMPT_LENGTH=${MAX_PROMPT_LENGTH} MAX_RESPONSE_LENGTH=${MAX_RESPONSE_LENGTH} MAX_MODEL_LEN=${MAX_MODEL_LEN} MAX_TOKENS_PER_TURN=${MAX_TOKENS_PER_TURN} ROLLOUT_GPU_MEMORY_UTILIZATION=${ROLLOUT_GPU_MEMORY_UTILIZATION} REWARD_MODE=${REWARD_MODE} ORM_SUCCESS_SCORE=${ORM_SUCCESS_SCORE} PAD_TO_MAX_RESPONSE_LENGTH=${PAD_TO_MAX_RESPONSE_LENGTH} SAVE_FREQ=${SAVE_FREQ} REMOVE_PREVIOUS_CKPT_IN_SAVE=${REMOVE_PREVIOUS_CKPT_IN_SAVE} MAX_LOCAL_CKPT_TO_KEEP=${MAX_LOCAL_CKPT_TO_KEEP} RESUME_MODE=${RESUME_MODE} RESUME_FROM_PATH=${RESUME_FROM_PATH} ENABLE_WMC=${ENABLE_WMC} WMC_COEFF=${WMC_COEFF} ENABLE_ERC=${ENABLE_ERC} ERC_MU_BASE=${ERC_MU_BASE} ERC_MU_EXP=${ERC_MU_EXP} ERC_ETA_WM=${ERC_ETA_WM} ERC_LAMBDA_WM=${ERC_LAMBDA_WM} ERC_CLIPPING_TYPE=${ERC_CLIPPING_TYPE} ERC_CLIPPING_METHOD=${ERC_CLIPPING_METHOD} ERC_MOMENTUM=${ERC_MOMENTUM} RAY_TMPDIR=${RAY_TMPDIR} TMPDIR=${TMPDIR} TMP=${TMP} TEMP=${TEMP} HF_HOME=${HF_HOME} TRANSFORMERS_CACHE=${TRANSFORMERS_CACHE} XDG_CACHE_HOME=${XDG_CACHE_HOME} WANDB_DIR=${WANDB_DIR} WANDB_CACHE_DIR=${WANDB_CACHE_DIR} WANDB_CONFIG_DIR=${WANDB_CONFIG_DIR} EXP_NAME=${EXP_NAME} LOG_PATH=${TRAIN_LOG} bash ${ROOT}/scripts/run_alfworld_ppo_train.sh"

echo "Environment tmux session: ${ENV_SESSION}"
echo "Training tmux session: ${TRAIN_SESSION}"
echo "ALFWorld service: ${ENV_ADDR}"
echo "Environment log: ${ENV_LOG}"
echo "Training log: ${TRAIN_LOG}"
