#!/usr/bin/env bash

set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
CONDA_SH="${CONDA_SH:-/home/yexuyan/miniconda3/etc/profile.d/conda.sh}"
TRAIN_ENV="${TRAIN_ENV:-/idfsdata/yexuyan/conda_envs/agentgym-rl-webshop}"

CUDA_VISIBLE_DEVICES="${CUDA_VISIBLE_DEVICES:-0,1}"
MODEL_PATH="${MODEL_PATH:-/idfsdata/yexuyan/AgentGym-RL/models/Qwen2.5-7B-Instruct}"
EMBEDDING_MODEL_PATH="${EMBEDDING_MODEL_PATH:-/idfsdata/yexuyan/AgentGym-RL/models/Qwen3-Embedding-8B}"
TRIPLET_FILE="${TRIPLET_FILE:-${ROOT}/AgentItemId/alfworld_rwml_train.jsonl}"

WANDB_MODE="${WANDB_MODE:-online}"
WANDB_ENTITY="${WANDB_ENTITY:-xuyan923r-renmin-university-of-china}"
WANDB_BASE_URL="${WANDB_BASE_URL:-https://api.wandb.ai}"
PROJECT_NAME="${PROJECT_NAME:-ALFWorld-RWML}"

# Appendix B.1 defaults for ALFWorld RWML
# - rollout trajectories per training task: N = 3 (data collection stage)
# - GRPO group size: 8
TRAIN_BATCH_SIZE="${TRAIN_BATCH_SIZE:-32}"
PPO_MINI_BATCH_SIZE="${PPO_MINI_BATCH_SIZE:-16}"
PPO_MICRO_BATCH_SIZE_PER_GPU="${PPO_MICRO_BATCH_SIZE_PER_GPU:-1}"
ROLLOUT_N="${ROLLOUT_N:-8}"
PPO_EPOCHS="${PPO_EPOCHS:-2}"
TOTAL_EPOCHS="${TOTAL_EPOCHS:-2}"
POLICY_LR="${POLICY_LR:-1e-6}"
KL_COEF="${KL_COEF:-0.001}"
RWML_TEMPERATURE="${RWML_TEMPERATURE:-1.0}"
RWML_THRESHOLD="${RWML_THRESHOLD:-0.2}"
RWML_ROUND_STEP="${RWML_ROUND_STEP:-0.2}"
MAX_PROMPT_LENGTH="${MAX_PROMPT_LENGTH:-2048}"
MAX_RESPONSE_LENGTH="${MAX_RESPONSE_LENGTH:-512}"
RWML_RESPONSE_LENGTH="${RWML_RESPONSE_LENGTH:-256}"
MAX_MODEL_LEN="${MAX_MODEL_LEN:-4096}"
ROLLOUT_GPU_MEMORY_UTILIZATION="${ROLLOUT_GPU_MEMORY_UTILIZATION:-0.70}"

TMPDIR="${TMPDIR:-/idfsdata/yexuyan/te}"
TMP="${TMP:-${TMPDIR}}"
TEMP="${TEMP:-${TMPDIR}}"
HF_HOME="${HF_HOME:-/idfsdata/yexuyan/he}"
TRANSFORMERS_CACHE="${TRANSFORMERS_CACHE:-${HF_HOME}/hub}"
XDG_CACHE_HOME="${XDG_CACHE_HOME:-/idfsdata/yexuyan/xe}"
WANDB_DIR="${WANDB_DIR:-/idfsdata/yexuyan/we}"
WANDB_CACHE_DIR="${WANDB_CACHE_DIR:-${WANDB_DIR}/.cache}"
WANDB_CONFIG_DIR="${WANDB_CONFIG_DIR:-${WANDB_DIR}/.config}"
RAY_TMPDIR="${RAY_TMPDIR:-/idfsdata/yexuyan/ra}"

RUN_TS="$(date -u +%Y%m%d_%H%M%S)"
EXP_NAME="${EXP_NAME:-ALFWORLD_RWML_Qwen25_7B_${RUN_TS}}"
TRAIN_SESSION="${TRAIN_SESSION:-alfworld_rwml_${RUN_TS}}"
TRAIN_LOG="${ROOT}/runlogs/${EXP_NAME}/train.log"

mkdir -p "${ROOT}/runlogs/${EXP_NAME}" "${TMPDIR}" "${HF_HOME}" "${TRANSFORMERS_CACHE}" "${XDG_CACHE_HOME}" "${WANDB_DIR}" "${WANDB_CACHE_DIR}" "${WANDB_CONFIG_DIR}" "${RAY_TMPDIR}"

if [[ -z "${EMBEDDING_MODEL_PATH}" ]]; then
  echo "EMBEDDING_MODEL_PATH must be set."
  exit 1
fi
if [[ ! -f "${TRIPLET_FILE}" ]]; then
  echo "Triplet file not found: ${TRIPLET_FILE}"
  exit 1
fi
if tmux has-session -t "${TRAIN_SESSION}" 2>/dev/null; then
  echo "tmux session already exists: ${TRAIN_SESSION}"
  exit 1
fi

tmux new-session -d -s "${TRAIN_SESSION}" \
  "cd ${ROOT} && CONDA_SH=${CONDA_SH} TRAIN_ENV=${TRAIN_ENV} CUDA_VISIBLE_DEVICES=${CUDA_VISIBLE_DEVICES} MODEL_PATH=${MODEL_PATH} EMBEDDING_MODEL_PATH=${EMBEDDING_MODEL_PATH} TRAIN_FILE=${TRIPLET_FILE} WANDB_MODE=${WANDB_MODE} WANDB_ENTITY=${WANDB_ENTITY} WANDB_BASE_URL=${WANDB_BASE_URL} PROJECT_NAME=${PROJECT_NAME} TRAIN_BATCH_SIZE=${TRAIN_BATCH_SIZE} PPO_MINI_BATCH_SIZE=${PPO_MINI_BATCH_SIZE} PPO_MICRO_BATCH_SIZE_PER_GPU=${PPO_MICRO_BATCH_SIZE_PER_GPU} ROLLOUT_N=${ROLLOUT_N} PPO_EPOCHS=${PPO_EPOCHS} TOTAL_EPOCHS=${TOTAL_EPOCHS} POLICY_LR=${POLICY_LR} KL_COEF=${KL_COEF} RWML_TEMPERATURE=${RWML_TEMPERATURE} RWML_THRESHOLD=${RWML_THRESHOLD} RWML_ROUND_STEP=${RWML_ROUND_STEP} MAX_PROMPT_LENGTH=${MAX_PROMPT_LENGTH} MAX_RESPONSE_LENGTH=${MAX_RESPONSE_LENGTH} RWML_RESPONSE_LENGTH=${RWML_RESPONSE_LENGTH} MAX_MODEL_LEN=${MAX_MODEL_LEN} ROLLOUT_GPU_MEMORY_UTILIZATION=${ROLLOUT_GPU_MEMORY_UTILIZATION} TMPDIR=${TMPDIR} TMP=${TMP} TEMP=${TEMP} HF_HOME=${HF_HOME} TRANSFORMERS_CACHE=${TRANSFORMERS_CACHE} XDG_CACHE_HOME=${XDG_CACHE_HOME} WANDB_DIR=${WANDB_DIR} WANDB_CACHE_DIR=${WANDB_CACHE_DIR} WANDB_CONFIG_DIR=${WANDB_CONFIG_DIR} RAY_TMPDIR=${RAY_TMPDIR} EXP_NAME=${EXP_NAME} LOG_PATH=${TRAIN_LOG} bash ${ROOT}/scripts/run_alfworld_rwml_train.sh"

echo "Training tmux session: ${TRAIN_SESSION}"
echo "Training log: ${TRAIN_LOG}"
echo "Triplet file: ${TRIPLET_FILE}"
